version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=davi
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=java-security